baseURL = "https://k-kaz-git.github.io/"
title = "k-kaz が Hugo で遊ぶサイト"
languageCode = "ja"
defaultContentLanguage = "ja"

theme = "aether"
googleAnalytics = "UA-134722453-1"
disqusShortname = "Your shortname for Disqus - optional"
enableGitInfo = true # 最終更新日をgit履歴から自動取得

[params]
brand = "k-kaz が Hugo で遊ぶサイト"

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = [":git", "lastmod", "date", "publishDate", ":fileModTime"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]

[taxonomies]
category = "categories"
tag = "tags"

[markup.goldmark.renderer]
unsafe= true
